[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
monitor_port = /dev/tty.usbmodem1101
monitor_rts = 0
monitor_dtr = 0
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1

[env:seeed_xiao_esp32c3_ota]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
monitor_port = /dev/tty.usbmodem1101
monitor_rts = 0
monitor_dtr = 0
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
upload_protocol = espota
upload_port = xiao-esp32c3-pid.local
